url: https://movarsun.github.io
baseurl: /

# Site settings
title: Asset  Right Co
email: assetright@assetright.co
description: "AssetRight Co. Expertise. Trust. Growth"

# Team names, titles and social links
people:
- name: Pappu Sundaramoorthy
  pic: 1
  position: Founder 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket 
    url: http://bitbucket.org/
  - title: github
    url: http://github.com/

# Postal address (add as many lines as necessary)
address:
  - line: NA
  - line: NA

# Build settings
markdown: kramdown
permalink: pretty